id: DE794B551
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:40:17+00:00'
last_modified: '2022-05-26T11:24:02.149413+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    8a00:
      image_group_id: I1PD95871
      title: རྗེ་བཙུན་མ་འཕགས་མ་སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1902
      order: 26
      base_file: 8a00.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
