id: 3549d72f9f8d455ba241d3dcaa66fccc
initial_creation_type: ocr
source_metadata:
  volumes:
    4a39a48d29ca43d8810d10fa271720d2:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
